//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AutoWhiteBalanceModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="AutoWhiteBalanceModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="AutoWhiteBalanceMode_PresetWhiteBalanceSetup"/>
 *     &lt;enumeration value="AutoWhiteBalanceMode_AutomaticWhiteBalanceSetup"/>
 *     &lt;enumeration value="AutoWhiteBalanceMode_HoldWhiteBalanceSetup"/>
 *     &lt;enumeration value="AutoWhiteBalanceMode_OnePushWhiteBalanceSetup"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "AutoWhiteBalanceModeType")
@XmlEnum
public enum AutoWhiteBalanceModeType {

    @XmlEnumValue("AutoWhiteBalanceMode_PresetWhiteBalanceSetup")
    AUTO_WHITE_BALANCE_MODE_PRESET_WHITE_BALANCE_SETUP("AutoWhiteBalanceMode_PresetWhiteBalanceSetup"),
    @XmlEnumValue("AutoWhiteBalanceMode_AutomaticWhiteBalanceSetup")
    AUTO_WHITE_BALANCE_MODE_AUTOMATIC_WHITE_BALANCE_SETUP("AutoWhiteBalanceMode_AutomaticWhiteBalanceSetup"),
    @XmlEnumValue("AutoWhiteBalanceMode_HoldWhiteBalanceSetup")
    AUTO_WHITE_BALANCE_MODE_HOLD_WHITE_BALANCE_SETUP("AutoWhiteBalanceMode_HoldWhiteBalanceSetup"),
    @XmlEnumValue("AutoWhiteBalanceMode_OnePushWhiteBalanceSetup")
    AUTO_WHITE_BALANCE_MODE_ONE_PUSH_WHITE_BALANCE_SETUP("AutoWhiteBalanceMode_OnePushWhiteBalanceSetup");
    private final String value;

    AutoWhiteBalanceModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static AutoWhiteBalanceModeType fromValue(String v) {
        for (AutoWhiteBalanceModeType c: AutoWhiteBalanceModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
