//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ChannelStatusModeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ChannelStatusModeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ChannelStatusMode_None"/>
 *     &lt;enumeration value="ChannelStatusMode_Minimum"/>
 *     &lt;enumeration value="ChannelStatusMode_Standard"/>
 *     &lt;enumeration value="ChannelStatusMode_Fixed"/>
 *     &lt;enumeration value="ChannelStatusMode_Stream"/>
 *     &lt;enumeration value="ChannelStatusMode_Essence"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ChannelStatusModeType")
@XmlEnum
public enum ChannelStatusModeType {

    @XmlEnumValue("ChannelStatusMode_None")
    CHANNEL_STATUS_MODE_NONE("ChannelStatusMode_None"),
    @XmlEnumValue("ChannelStatusMode_Minimum")
    CHANNEL_STATUS_MODE_MINIMUM("ChannelStatusMode_Minimum"),
    @XmlEnumValue("ChannelStatusMode_Standard")
    CHANNEL_STATUS_MODE_STANDARD("ChannelStatusMode_Standard"),
    @XmlEnumValue("ChannelStatusMode_Fixed")
    CHANNEL_STATUS_MODE_FIXED("ChannelStatusMode_Fixed"),
    @XmlEnumValue("ChannelStatusMode_Stream")
    CHANNEL_STATUS_MODE_STREAM("ChannelStatusMode_Stream"),
    @XmlEnumValue("ChannelStatusMode_Essence")
    CHANNEL_STATUS_MODE_ESSENCE("ChannelStatusMode_Essence");
    private final String value;

    ChannelStatusModeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ChannelStatusModeType fromValue(String v) {
        for (ChannelStatusModeType c: ChannelStatusModeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
