//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._395._2014._13._1.aaf.NetworkLocator;
import org.smpte_ra.reg._395._2014._13._1.aaf.TextLocator;


/**
 * <p>Java class for LocatorStrongReferenceVector complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LocatorStrongReferenceVector">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://www.smpte-ra.org/reg/395/2014/13/1/aaf}TextLocator"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/395/2014/13/1/aaf}NetworkLocator"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LocatorStrongReferenceVector", propOrder = {
    "textLocatorOrNetworkLocator"
})
public class LocatorStrongReferenceVector {

    @XmlElements({
        @XmlElement(name = "TextLocator", namespace = "http://www.smpte-ra.org/reg/395/2014/13/1/aaf", type = TextLocator.class),
        @XmlElement(name = "NetworkLocator", namespace = "http://www.smpte-ra.org/reg/395/2014/13/1/aaf", type = NetworkLocator.class)
    })
    protected List<Object> textLocatorOrNetworkLocator;

    /**
     * Gets the value of the textLocatorOrNetworkLocator property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the textLocatorOrNetworkLocator property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTextLocatorOrNetworkLocator().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TextLocator }
     * {@link NetworkLocator }
     * 
     * 
     */
    public List<Object> getTextLocatorOrNetworkLocator() {
        if (textLocatorOrNetworkLocator == null) {
            textLocatorOrNetworkLocator = new ArrayList<Object>();
        }
        return this.textLocatorOrNetworkLocator;
    }

}
