//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.smpte-ra.org/reg/2003/2012", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.smpte_ra.reg._2003._2012;
