//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TapeCaseType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TapeCaseType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="TapeCaseNull"/>
 *     &lt;enumeration value="ThreeFourthInchVideoTape"/>
 *     &lt;enumeration value="VHSVideoTape"/>
 *     &lt;enumeration value="EightMillimeterVideoTape"/>
 *     &lt;enumeration value="BetacamVideoTape"/>
 *     &lt;enumeration value="CompactCassette"/>
 *     &lt;enumeration value="DATCartridge"/>
 *     &lt;enumeration value="NagraAudioTape"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TapeCaseType")
@XmlEnum
public enum TapeCaseType {

    @XmlEnumValue("TapeCaseNull")
    TAPE_CASE_NULL("TapeCaseNull"),
    @XmlEnumValue("ThreeFourthInchVideoTape")
    THREE_FOURTH_INCH_VIDEO_TAPE("ThreeFourthInchVideoTape"),
    @XmlEnumValue("VHSVideoTape")
    VHS_VIDEO_TAPE("VHSVideoTape"),
    @XmlEnumValue("EightMillimeterVideoTape")
    EIGHT_MILLIMETER_VIDEO_TAPE("EightMillimeterVideoTape"),
    @XmlEnumValue("BetacamVideoTape")
    BETACAM_VIDEO_TAPE("BetacamVideoTape"),
    @XmlEnumValue("CompactCassette")
    COMPACT_CASSETTE("CompactCassette"),
    @XmlEnumValue("DATCartridge")
    DAT_CARTRIDGE("DATCartridge"),
    @XmlEnumValue("NagraAudioTape")
    NAGRA_AUDIO_TAPE("NagraAudioTape");
    private final String value;

    TapeCaseType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TapeCaseType fromValue(String v) {
        for (TapeCaseType c: TapeCaseType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
