//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TIFFPhotometricInterpretationKindType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TIFFPhotometricInterpretationKindType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="TIFFPhotometricInterpretationKind_ColorFilterArray"/>
 *     &lt;enumeration value="TIFFPhotometricInterpretationKind_LinearRaw"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TIFFPhotometricInterpretationKindType")
@XmlEnum
public enum TIFFPhotometricInterpretationKindType {

    @XmlEnumValue("TIFFPhotometricInterpretationKind_ColorFilterArray")
    TIFF_PHOTOMETRIC_INTERPRETATION_KIND_COLOR_FILTER_ARRAY("TIFFPhotometricInterpretationKind_ColorFilterArray"),
    @XmlEnumValue("TIFFPhotometricInterpretationKind_LinearRaw")
    TIFF_PHOTOMETRIC_INTERPRETATION_KIND_LINEAR_RAW("TIFFPhotometricInterpretationKind_LinearRaw");
    private final String value;

    TIFFPhotometricInterpretationKindType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TIFFPhotometricInterpretationKindType fromValue(String v) {
        for (TIFFPhotometricInterpretationKindType c: TIFFPhotometricInterpretationKindType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
