//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TIFFByteOrderType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TIFFByteOrderType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="TIFFByteOrder_BigEndian"/>
 *     &lt;enumeration value="TIFFByteOrder_LittleEndian"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "TIFFByteOrderType")
@XmlEnum
public enum TIFFByteOrderType {

    @XmlEnumValue("TIFFByteOrder_BigEndian")
    TIFF_BYTE_ORDER_BIG_ENDIAN("TIFFByteOrder_BigEndian"),
    @XmlEnumValue("TIFFByteOrder_LittleEndian")
    TIFF_BYTE_ORDER_LITTLE_ENDIAN("TIFFByteOrder_LittleEndian");
    private final String value;

    TIFFByteOrderType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static TIFFByteOrderType fromValue(String v) {
        for (TIFFByteOrderType c: TIFFByteOrderType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
