//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._395._2014._13._1.aaf.EventTrack;
import org.smpte_ra.reg._395._2014._13._1.aaf.StaticTrack;
import org.smpte_ra.reg._395._2014._13._1.aaf.TimelineTrack;


/**
 * <p>Java class for TrackStrongReference complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TrackStrongReference">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/395/2014/13/1/aaf}EventTrack"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/395/2014/13/1/aaf}StaticTrack"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/395/2014/13/1/aaf}TimelineTrack"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TrackStrongReference", propOrder = {
    "eventTrack",
    "staticTrack",
    "timelineTrack"
})
public class TrackStrongReference {

    @XmlElement(name = "EventTrack", namespace = "http://www.smpte-ra.org/reg/395/2014/13/1/aaf")
    protected EventTrack eventTrack;
    @XmlElement(name = "StaticTrack", namespace = "http://www.smpte-ra.org/reg/395/2014/13/1/aaf")
    protected StaticTrack staticTrack;
    @XmlElement(name = "TimelineTrack", namespace = "http://www.smpte-ra.org/reg/395/2014/13/1/aaf")
    protected TimelineTrack timelineTrack;

    /**
     * Gets the value of the eventTrack property.
     * 
     * @return
     *     possible object is
     *     {@link EventTrack }
     *     
     */
    public EventTrack getEventTrack() {
        return eventTrack;
    }

    /**
     * Sets the value of the eventTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTrack }
     *     
     */
    public void setEventTrack(EventTrack value) {
        this.eventTrack = value;
    }

    /**
     * Gets the value of the staticTrack property.
     * 
     * @return
     *     possible object is
     *     {@link StaticTrack }
     *     
     */
    public StaticTrack getStaticTrack() {
        return staticTrack;
    }

    /**
     * Sets the value of the staticTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link StaticTrack }
     *     
     */
    public void setStaticTrack(StaticTrack value) {
        this.staticTrack = value;
    }

    /**
     * Gets the value of the timelineTrack property.
     * 
     * @return
     *     possible object is
     *     {@link TimelineTrack }
     *     
     */
    public TimelineTrack getTimelineTrack() {
        return timelineTrack;
    }

    /**
     * Sets the value of the timelineTrack property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimelineTrack }
     *     
     */
    public void setTimelineTrack(TimelineTrack value) {
        this.timelineTrack = value;
    }

}
