//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._335._2012._13._1.amwa.as11;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import org.smpte_ra.reg._2003._2012.Boolean;
import org.smpte_ra.reg._2003._2012.UTF16String;
import org.smpte_ra.reg._2003._2012._13._1.amwa.as11.AS11AudioTrackLayoutEnum;
import org.smpte_ra.reg._2003._2012._13._1.amwa.as11.AS11CaptionsTypeEnum;
import org.smpte_ra.reg._2003._2012._13._1.amwa.as11.ISO6392LanguageCode;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.smpte_ra.reg._335._2012._13._1.amwa.as11 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _AS11ShimVersion_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Shim_Version");
    private final static QName _AS11PrimaryAudioLanguage_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Primary_Audio_Language");
    private final static QName _AS11CaptionLanguage_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Caption_Language");
    private final static QName _AS11ClosedCaptionsType_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Closed_Captions_Type");
    private final static QName _AS11ProgrammeTitle_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Programme_Title");
    private final static QName _AS11PartTotal_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Part_Total");
    private final static QName _AS11AudioTrackLayout_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Audio_Track_Layout");
    private final static QName _AS11ShimName_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Shim_Name");
    private final static QName _AS11PartNumber_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Part_Number");
    private final static QName _AS11EpisodeTitleNumber_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Episode_Title_Number");
    private final static QName _AS11SeriesTitle_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Series_Title");
    private final static QName _AS11ClosedCaptionsPresent_QNAME = new QName("http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", "AS_11_Closed_Captions_Present");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.smpte_ra.reg._335._2012._13._1.amwa.as11
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Shim_Version")
    public JAXBElement<String> createAS11ShimVersion(String value) {
        return new JAXBElement<String>(_AS11ShimVersion_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO6392LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Primary_Audio_Language")
    public JAXBElement<ISO6392LanguageCode> createAS11PrimaryAudioLanguage(ISO6392LanguageCode value) {
        return new JAXBElement<ISO6392LanguageCode>(_AS11PrimaryAudioLanguage_QNAME, ISO6392LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ISO6392LanguageCode }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Caption_Language")
    public JAXBElement<ISO6392LanguageCode> createAS11CaptionLanguage(ISO6392LanguageCode value) {
        return new JAXBElement<ISO6392LanguageCode>(_AS11CaptionLanguage_QNAME, ISO6392LanguageCode.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AS11CaptionsTypeEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Closed_Captions_Type")
    public JAXBElement<AS11CaptionsTypeEnum> createAS11ClosedCaptionsType(AS11CaptionsTypeEnum value) {
        return new JAXBElement<AS11CaptionsTypeEnum>(_AS11ClosedCaptionsType_QNAME, AS11CaptionsTypeEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UTF16String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Programme_Title")
    public JAXBElement<UTF16String> createAS11ProgrammeTitle(UTF16String value) {
        return new JAXBElement<UTF16String>(_AS11ProgrammeTitle_QNAME, UTF16String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Part_Total")
    public JAXBElement<String> createAS11PartTotal(String value) {
        return new JAXBElement<String>(_AS11PartTotal_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AS11AudioTrackLayoutEnum }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Audio_Track_Layout")
    public JAXBElement<AS11AudioTrackLayoutEnum> createAS11AudioTrackLayout(AS11AudioTrackLayoutEnum value) {
        return new JAXBElement<AS11AudioTrackLayoutEnum>(_AS11AudioTrackLayout_QNAME, AS11AudioTrackLayoutEnum.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UTF16String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Shim_Name")
    public JAXBElement<UTF16String> createAS11ShimName(UTF16String value) {
        return new JAXBElement<UTF16String>(_AS11ShimName_QNAME, UTF16String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Part_Number")
    public JAXBElement<String> createAS11PartNumber(String value) {
        return new JAXBElement<String>(_AS11PartNumber_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UTF16String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Episode_Title_Number")
    public JAXBElement<UTF16String> createAS11EpisodeTitleNumber(UTF16String value) {
        return new JAXBElement<UTF16String>(_AS11EpisodeTitleNumber_QNAME, UTF16String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link UTF16String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Series_Title")
    public JAXBElement<UTF16String> createAS11SeriesTitle(UTF16String value) {
        return new JAXBElement<UTF16String>(_AS11SeriesTitle_QNAME, UTF16String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Boolean }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.smpte-ra.org/reg/335/2012/13/1/amwa/as11", name = "AS_11_Closed_Captions_Present")
    public JAXBElement<Boolean> createAS11ClosedCaptionsPresent(Boolean value) {
        return new JAXBElement<Boolean>(_AS11ClosedCaptionsPresent_QNAME, Boolean.class, null, value);
    }

}
