//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7-b41 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.09.01 at 06:27:35 PM MSK 
//


package com.apple.itunes.importer.tv;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for CloneAssetList complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CloneAssetList">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{http://apple.com/itunes/importer}clone_asset"/>
 *         &lt;element ref="{http://apple.com/itunes/importer}clone_chapters"/>
 *       &lt;/choice>
 *       &lt;attribute name="container_id" type="{http://apple.com/itunes/importer}VendorIdType" />
 *       &lt;attribute name="media_type">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="video"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="origin_provider" use="required" type="{http://apple.com/itunes/importer}ProviderType" />
 *       &lt;attribute name="origin_vendor_id" use="required" type="{http://apple.com/itunes/importer}VendorIdType" />
 *       &lt;attribute name="target_vendor_id" type="{http://apple.com/itunes/importer}VendorIdType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CloneAssetList", propOrder = {
    "cloneAssetOrCloneChapters"
})
public class CloneAssetList {

    @XmlElements({
        @XmlElement(name = "clone_asset", type = CloneAssetItem.class),
        @XmlElement(name = "clone_chapters", type = String.class)
    })
    protected List<Object> cloneAssetOrCloneChapters;
    @XmlAttribute(name = "container_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String containerId;
    @XmlAttribute(name = "media_type")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mediaType;
    @XmlAttribute(name = "origin_provider", required = true)
    protected String originProvider;
    @XmlAttribute(name = "origin_vendor_id", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String originVendorId;
    @XmlAttribute(name = "target_vendor_id")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String targetVendorId;

    /**
     * Gets the value of the cloneAssetOrCloneChapters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the cloneAssetOrCloneChapters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCloneAssetOrCloneChapters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CloneAssetItem }
     * {@link String }
     * 
     * 
     */
    public List<Object> getCloneAssetOrCloneChapters() {
        if (cloneAssetOrCloneChapters == null) {
            cloneAssetOrCloneChapters = new ArrayList<Object>();
        }
        return this.cloneAssetOrCloneChapters;
    }

    /**
     * Gets the value of the containerId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerId() {
        return containerId;
    }

    /**
     * Sets the value of the containerId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerId(String value) {
        this.containerId = value;
    }

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

    /**
     * Gets the value of the originProvider property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginProvider() {
        return originProvider;
    }

    /**
     * Sets the value of the originProvider property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginProvider(String value) {
        this.originProvider = value;
    }

    /**
     * Gets the value of the originVendorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOriginVendorId() {
        return originVendorId;
    }

    /**
     * Sets the value of the originVendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOriginVendorId(String value) {
        this.originVendorId = value;
    }

    /**
     * Gets the value of the targetVendorId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetVendorId() {
        return targetVendorId;
    }

    /**
     * Sets the value of the targetVendorId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetVendorId(String value) {
        this.targetVendorId = value;
    }

}
