#!/usr/bin/env bash

function usage {
    echo "Converts a test package to iTunes format."
    echo "1st argument - a path to the directory containing the test packages."
    echo "2d argument - a path to the directory containing the output for the test packages."
    echo "3d argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
}

if [ -z "$1" ]; then
    echo "Missing argument: a path to the directory containing the test packages."
    usage
    exit 1
fi
if [ -z "$2" ]; then
    echo "Missing argument: a path to the directory containing the output for the test packages."
    usage
    exit 1
fi


