//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.CodecDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.ContainerDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.DataDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.InterpolationDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.KLVDataDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.OperationDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.ParameterDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.PluginDefinitionStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.TaggedValueDefinitionStrongReferenceSet;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}DataDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ParameterDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}OperationDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}TaggedValueDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}KLVDataDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InterpolationDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ContainerDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}CodecDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}PluginDefinitions" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Dictionary")
public class Dictionary {

    @XmlElement(name = "DataDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected DataDefinitionStrongReferenceSet dataDefinitions;
    @XmlElement(name = "ParameterDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ParameterDefinitionStrongReferenceSet parameterDefinitions;
    @XmlElement(name = "OperationDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected OperationDefinitionStrongReferenceSet operationDefinitions;
    @XmlElement(name = "TaggedValueDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected TaggedValueDefinitionStrongReferenceSet taggedValueDefinitions;
    @XmlElement(name = "KLVDataDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected KLVDataDefinitionStrongReferenceSet klvDataDefinitions;
    @XmlElement(name = "InterpolationDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected InterpolationDefinitionStrongReferenceSet interpolationDefinitions;
    @XmlElement(name = "ContainerDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ContainerDefinitionStrongReferenceSet containerDefinitions;
    @XmlElement(name = "CodecDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected CodecDefinitionStrongReferenceSet codecDefinitions;
    @XmlElement(name = "PluginDefinitions", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected PluginDefinitionStrongReferenceSet pluginDefinitions;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the dataDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link DataDefinitionStrongReferenceSet }
     *     
     */
    public DataDefinitionStrongReferenceSet getDataDefinitions() {
        return dataDefinitions;
    }

    /**
     * Sets the value of the dataDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataDefinitionStrongReferenceSet }
     *     
     */
    public void setDataDefinitions(DataDefinitionStrongReferenceSet value) {
        this.dataDefinitions = value;
    }

    /**
     * Gets the value of the parameterDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ParameterDefinitionStrongReferenceSet }
     *     
     */
    public ParameterDefinitionStrongReferenceSet getParameterDefinitions() {
        return parameterDefinitions;
    }

    /**
     * Sets the value of the parameterDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ParameterDefinitionStrongReferenceSet }
     *     
     */
    public void setParameterDefinitions(ParameterDefinitionStrongReferenceSet value) {
        this.parameterDefinitions = value;
    }

    /**
     * Gets the value of the operationDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link OperationDefinitionStrongReferenceSet }
     *     
     */
    public OperationDefinitionStrongReferenceSet getOperationDefinitions() {
        return operationDefinitions;
    }

    /**
     * Sets the value of the operationDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link OperationDefinitionStrongReferenceSet }
     *     
     */
    public void setOperationDefinitions(OperationDefinitionStrongReferenceSet value) {
        this.operationDefinitions = value;
    }

    /**
     * Gets the value of the taggedValueDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link TaggedValueDefinitionStrongReferenceSet }
     *     
     */
    public TaggedValueDefinitionStrongReferenceSet getTaggedValueDefinitions() {
        return taggedValueDefinitions;
    }

    /**
     * Sets the value of the taggedValueDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaggedValueDefinitionStrongReferenceSet }
     *     
     */
    public void setTaggedValueDefinitions(TaggedValueDefinitionStrongReferenceSet value) {
        this.taggedValueDefinitions = value;
    }

    /**
     * Gets the value of the klvDataDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link KLVDataDefinitionStrongReferenceSet }
     *     
     */
    public KLVDataDefinitionStrongReferenceSet getKLVDataDefinitions() {
        return klvDataDefinitions;
    }

    /**
     * Sets the value of the klvDataDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link KLVDataDefinitionStrongReferenceSet }
     *     
     */
    public void setKLVDataDefinitions(KLVDataDefinitionStrongReferenceSet value) {
        this.klvDataDefinitions = value;
    }

    /**
     * Gets the value of the interpolationDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link InterpolationDefinitionStrongReferenceSet }
     *     
     */
    public InterpolationDefinitionStrongReferenceSet getInterpolationDefinitions() {
        return interpolationDefinitions;
    }

    /**
     * Sets the value of the interpolationDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link InterpolationDefinitionStrongReferenceSet }
     *     
     */
    public void setInterpolationDefinitions(InterpolationDefinitionStrongReferenceSet value) {
        this.interpolationDefinitions = value;
    }

    /**
     * Gets the value of the containerDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link ContainerDefinitionStrongReferenceSet }
     *     
     */
    public ContainerDefinitionStrongReferenceSet getContainerDefinitions() {
        return containerDefinitions;
    }

    /**
     * Sets the value of the containerDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContainerDefinitionStrongReferenceSet }
     *     
     */
    public void setContainerDefinitions(ContainerDefinitionStrongReferenceSet value) {
        this.containerDefinitions = value;
    }

    /**
     * Gets the value of the codecDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link CodecDefinitionStrongReferenceSet }
     *     
     */
    public CodecDefinitionStrongReferenceSet getCodecDefinitions() {
        return codecDefinitions;
    }

    /**
     * Sets the value of the codecDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodecDefinitionStrongReferenceSet }
     *     
     */
    public void setCodecDefinitions(CodecDefinitionStrongReferenceSet value) {
        this.codecDefinitions = value;
    }

    /**
     * Gets the value of the pluginDefinitions property.
     * 
     * @return
     *     possible object is
     *     {@link PluginDefinitionStrongReferenceSet }
     *     
     */
    public PluginDefinitionStrongReferenceSet getPluginDefinitions() {
        return pluginDefinitions;
    }

    /**
     * Sets the value of the pluginDefinitions property.
     * 
     * @param value
     *     allowed object is
     *     {@link PluginDefinitionStrongReferenceSet }
     *     
     */
    public void setPluginDefinitions(PluginDefinitionStrongReferenceSet value) {
        this.pluginDefinitions = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
