//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.FilmType;
import org.smpte_ra.reg._2003._2012.LocatorStrongReferenceVector;
import org.smpte_ra.reg._2003._2012.SubDescriptorStrongReferenceVector;
import org.smpte_ra.reg._2003._2012.UTF16String;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FrameRate" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmStockKind" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmStockManufacturer" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}PerforationsPerFrame" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmAspectRatio" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmFormatName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmFormat" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FilmBatchNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}SubDescriptors" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}Locators" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "FilmDescriptor")
public class FilmDescriptor {

    @XmlElement(name = "FrameRate", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String frameRate;
    @XmlElement(name = "FilmStockKind", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String filmStockKind;
    @XmlElement(name = "FilmStockManufacturer", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String filmStockManufacturer;
    @XmlElement(name = "PerforationsPerFrame", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String perforationsPerFrame;
    @XmlElement(name = "FilmAspectRatio", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected String filmAspectRatio;
    @XmlElement(name = "FilmFormatName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String filmFormatName;
    @XmlElement(name = "FilmFormat", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "token")
    protected FilmType filmFormat;
    @XmlElement(name = "FilmBatchNumber", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String filmBatchNumber;
    @XmlElement(name = "SubDescriptors", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected SubDescriptorStrongReferenceVector subDescriptors;
    @XmlElement(name = "Locators", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected LocatorStrongReferenceVector locators;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the frameRate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameRate() {
        return frameRate;
    }

    /**
     * Sets the value of the frameRate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameRate(String value) {
        this.frameRate = value;
    }

    /**
     * Gets the value of the filmStockKind property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFilmStockKind() {
        return filmStockKind;
    }

    /**
     * Sets the value of the filmStockKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFilmStockKind(UTF16String value) {
        this.filmStockKind = value;
    }

    /**
     * Gets the value of the filmStockManufacturer property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFilmStockManufacturer() {
        return filmStockManufacturer;
    }

    /**
     * Sets the value of the filmStockManufacturer property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFilmStockManufacturer(UTF16String value) {
        this.filmStockManufacturer = value;
    }

    /**
     * Gets the value of the perforationsPerFrame property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPerforationsPerFrame() {
        return perforationsPerFrame;
    }

    /**
     * Sets the value of the perforationsPerFrame property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPerforationsPerFrame(String value) {
        this.perforationsPerFrame = value;
    }

    /**
     * Gets the value of the filmAspectRatio property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFilmAspectRatio() {
        return filmAspectRatio;
    }

    /**
     * Sets the value of the filmAspectRatio property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFilmAspectRatio(String value) {
        this.filmAspectRatio = value;
    }

    /**
     * Gets the value of the filmFormatName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFilmFormatName() {
        return filmFormatName;
    }

    /**
     * Sets the value of the filmFormatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFilmFormatName(UTF16String value) {
        this.filmFormatName = value;
    }

    /**
     * Gets the value of the filmFormat property.
     * 
     * @return
     *     possible object is
     *     {@link FilmType }
     *     
     */
    public FilmType getFilmFormat() {
        return filmFormat;
    }

    /**
     * Sets the value of the filmFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link FilmType }
     *     
     */
    public void setFilmFormat(FilmType value) {
        this.filmFormat = value;
    }

    /**
     * Gets the value of the filmBatchNumber property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFilmBatchNumber() {
        return filmBatchNumber;
    }

    /**
     * Sets the value of the filmBatchNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFilmBatchNumber(UTF16String value) {
        this.filmBatchNumber = value;
    }

    /**
     * Gets the value of the subDescriptors property.
     * 
     * @return
     *     possible object is
     *     {@link SubDescriptorStrongReferenceVector }
     *     
     */
    public SubDescriptorStrongReferenceVector getSubDescriptors() {
        return subDescriptors;
    }

    /**
     * Sets the value of the subDescriptors property.
     * 
     * @param value
     *     allowed object is
     *     {@link SubDescriptorStrongReferenceVector }
     *     
     */
    public void setSubDescriptors(SubDescriptorStrongReferenceVector value) {
        this.subDescriptors = value;
    }

    /**
     * Gets the value of the locators property.
     * 
     * @return
     *     possible object is
     *     {@link LocatorStrongReferenceVector }
     *     
     */
    public LocatorStrongReferenceVector getLocators() {
        return locators;
    }

    /**
     * Sets the value of the locators property.
     * 
     * @param value
     *     allowed object is
     *     {@link LocatorStrongReferenceVector }
     *     
     */
    public void setLocators(LocatorStrongReferenceVector value) {
        this.locators = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
