//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.DescriptiveObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.NameValueStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.OrganizationGlobalReferenceSet;
import org.smpte_ra.reg._2003._2012.UTF16String;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}Citizenship" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}HonorsQualifications" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}PersonDescription" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}OtherGivenNames" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}AlternateName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkingName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}NameSuffix" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FormerFamilyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}Nationality" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FamilyName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}FirstGivenName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}PersonOrganizations" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}Salutation" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}AddressObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ContactID"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ContactNameValueObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ThesaurusName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedDescriptiveObjectPluginID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}uid use="required""/>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Person")
public class Person {

    @XmlElement(name = "Citizenship", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String citizenship;
    @XmlElement(name = "HonorsQualifications", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String honorsQualifications;
    @XmlElement(name = "PersonDescription", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String personDescription;
    @XmlElement(name = "OtherGivenNames", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String otherGivenNames;
    @XmlElement(name = "AlternateName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String alternateName;
    @XmlElement(name = "LinkingName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String linkingName;
    @XmlElement(name = "NameSuffix", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String nameSuffix;
    @XmlElement(name = "FormerFamilyName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String formerFamilyName;
    @XmlElement(name = "Nationality", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String nationality;
    @XmlElement(name = "FamilyName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String familyName;
    @XmlElement(name = "FirstGivenName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String firstGivenName;
    @XmlElement(name = "PersonOrganizations", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected OrganizationGlobalReferenceSet personOrganizations;
    @XmlElement(name = "Salutation", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String salutation;
    @XmlElement(name = "AddressObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected DescriptiveObjectStrongReferenceSet addressObjects;
    @XmlElement(name = "ContactID", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String contactID;
    @XmlElement(name = "ContactNameValueObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected NameValueStrongReferenceSet contactNameValueObjects;
    @XmlElement(name = "ThesaurusName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String thesaurusName;
    @XmlElement(name = "LinkedDescriptiveObjectPluginID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkedDescriptiveObjectPluginID;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "uid", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline", required = true)
    protected String uid;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the citizenship property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getCitizenship() {
        return citizenship;
    }

    /**
     * Sets the value of the citizenship property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setCitizenship(UTF16String value) {
        this.citizenship = value;
    }

    /**
     * Gets the value of the honorsQualifications property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getHonorsQualifications() {
        return honorsQualifications;
    }

    /**
     * Sets the value of the honorsQualifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setHonorsQualifications(UTF16String value) {
        this.honorsQualifications = value;
    }

    /**
     * Gets the value of the personDescription property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getPersonDescription() {
        return personDescription;
    }

    /**
     * Sets the value of the personDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setPersonDescription(UTF16String value) {
        this.personDescription = value;
    }

    /**
     * Gets the value of the otherGivenNames property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getOtherGivenNames() {
        return otherGivenNames;
    }

    /**
     * Sets the value of the otherGivenNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setOtherGivenNames(UTF16String value) {
        this.otherGivenNames = value;
    }

    /**
     * Gets the value of the alternateName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getAlternateName() {
        return alternateName;
    }

    /**
     * Sets the value of the alternateName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setAlternateName(UTF16String value) {
        this.alternateName = value;
    }

    /**
     * Gets the value of the linkingName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getLinkingName() {
        return linkingName;
    }

    /**
     * Sets the value of the linkingName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setLinkingName(UTF16String value) {
        this.linkingName = value;
    }

    /**
     * Gets the value of the nameSuffix property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getNameSuffix() {
        return nameSuffix;
    }

    /**
     * Sets the value of the nameSuffix property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setNameSuffix(UTF16String value) {
        this.nameSuffix = value;
    }

    /**
     * Gets the value of the formerFamilyName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFormerFamilyName() {
        return formerFamilyName;
    }

    /**
     * Sets the value of the formerFamilyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFormerFamilyName(UTF16String value) {
        this.formerFamilyName = value;
    }

    /**
     * Gets the value of the nationality property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getNationality() {
        return nationality;
    }

    /**
     * Sets the value of the nationality property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setNationality(UTF16String value) {
        this.nationality = value;
    }

    /**
     * Gets the value of the familyName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFamilyName() {
        return familyName;
    }

    /**
     * Sets the value of the familyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFamilyName(UTF16String value) {
        this.familyName = value;
    }

    /**
     * Gets the value of the firstGivenName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getFirstGivenName() {
        return firstGivenName;
    }

    /**
     * Sets the value of the firstGivenName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setFirstGivenName(UTF16String value) {
        this.firstGivenName = value;
    }

    /**
     * Gets the value of the personOrganizations property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationGlobalReferenceSet }
     *     
     */
    public OrganizationGlobalReferenceSet getPersonOrganizations() {
        return personOrganizations;
    }

    /**
     * Sets the value of the personOrganizations property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationGlobalReferenceSet }
     *     
     */
    public void setPersonOrganizations(OrganizationGlobalReferenceSet value) {
        this.personOrganizations = value;
    }

    /**
     * Gets the value of the salutation property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getSalutation() {
        return salutation;
    }

    /**
     * Sets the value of the salutation property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setSalutation(UTF16String value) {
        this.salutation = value;
    }

    /**
     * Gets the value of the addressObjects property.
     * 
     * @return
     *     possible object is
     *     {@link DescriptiveObjectStrongReferenceSet }
     *     
     */
    public DescriptiveObjectStrongReferenceSet getAddressObjects() {
        return addressObjects;
    }

    /**
     * Sets the value of the addressObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link DescriptiveObjectStrongReferenceSet }
     *     
     */
    public void setAddressObjects(DescriptiveObjectStrongReferenceSet value) {
        this.addressObjects = value;
    }

    /**
     * Gets the value of the contactID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContactID() {
        return contactID;
    }

    /**
     * Sets the value of the contactID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContactID(String value) {
        this.contactID = value;
    }

    /**
     * Gets the value of the contactNameValueObjects property.
     * 
     * @return
     *     possible object is
     *     {@link NameValueStrongReferenceSet }
     *     
     */
    public NameValueStrongReferenceSet getContactNameValueObjects() {
        return contactNameValueObjects;
    }

    /**
     * Sets the value of the contactNameValueObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link NameValueStrongReferenceSet }
     *     
     */
    public void setContactNameValueObjects(NameValueStrongReferenceSet value) {
        this.contactNameValueObjects = value;
    }

    /**
     * Gets the value of the thesaurusName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getThesaurusName() {
        return thesaurusName;
    }

    /**
     * Sets the value of the thesaurusName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setThesaurusName(UTF16String value) {
        this.thesaurusName = value;
    }

    /**
     * Gets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedDescriptiveObjectPluginID() {
        return linkedDescriptiveObjectPluginID;
    }

    /**
     * Sets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedDescriptiveObjectPluginID(String value) {
        this.linkedDescriptiveObjectPluginID = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
