//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.MetaDictionaryStrongReference;
import org.smpte_ra.reg._2003._2012.PrefaceStrongReference;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}RootObjectDirectory" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}RootPreface"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}RootFormatVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}RootMetaDictionary"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "Root")
public class Root {

    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "RootObjectDirectory", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected String rootObjectDirectory;
    @XmlElement(name = "RootPreface", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected PrefaceStrongReference rootPreface;
    @XmlElement(name = "RootFormatVersion", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String rootFormatVersion;
    @XmlElement(name = "RootMetaDictionary", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected MetaDictionaryStrongReference rootMetaDictionary;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the rootObjectDirectory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootObjectDirectory() {
        return rootObjectDirectory;
    }

    /**
     * Sets the value of the rootObjectDirectory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootObjectDirectory(String value) {
        this.rootObjectDirectory = value;
    }

    /**
     * Gets the value of the rootPreface property.
     * 
     * @return
     *     possible object is
     *     {@link PrefaceStrongReference }
     *     
     */
    public PrefaceStrongReference getRootPreface() {
        return rootPreface;
    }

    /**
     * Sets the value of the rootPreface property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrefaceStrongReference }
     *     
     */
    public void setRootPreface(PrefaceStrongReference value) {
        this.rootPreface = value;
    }

    /**
     * Gets the value of the rootFormatVersion property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRootFormatVersion() {
        return rootFormatVersion;
    }

    /**
     * Sets the value of the rootFormatVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRootFormatVersion(String value) {
        this.rootFormatVersion = value;
    }

    /**
     * Gets the value of the rootMetaDictionary property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDictionaryStrongReference }
     *     
     */
    public MetaDictionaryStrongReference getRootMetaDictionary() {
        return rootMetaDictionary;
    }

    /**
     * Sets the value of the rootMetaDictionary property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDictionaryStrongReference }
     *     
     */
    public void setRootMetaDictionary(MetaDictionaryStrongReference value) {
        this.rootMetaDictionary = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
