//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.ISO7;
import org.smpte_ra.reg._2003._2012.UTF16String;
import org.smpte_ra.reg._2003._2012.UUIDArray;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}GroupOfSoundfieldGroupsLinkID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCALinkID"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCATagName" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCATitle" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCATitleSubVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCALabelDictionaryID"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCATagSymbol"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}RFC5646SpokenLanguage" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAPartitionNumber" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAPartitionKind" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCATitleVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAAudioElementKind" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAAudioContentKind" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAEpisode" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MCAChannelID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "SoundfieldGroupLabelSubDescriptor")
public class SoundfieldGroupLabelSubDescriptor {

    @XmlElement(name = "GroupOfSoundfieldGroupsLinkID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UUIDArray groupOfSoundfieldGroupsLinkID;
    @XmlElement(name = "MCALinkID", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String mcaLinkID;
    @XmlElement(name = "MCATagName", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaTagName;
    @XmlElement(name = "MCATitle", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaTitle;
    @XmlElement(name = "MCATitleSubVersion", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaTitleSubVersion;
    @XmlElement(name = "MCALabelDictionaryID", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String mcaLabelDictionaryID;
    @XmlElement(name = "MCATagSymbol", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected UTF16String mcaTagSymbol;
    @XmlElement(name = "RFC5646SpokenLanguage", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ISO7 rfc5646SpokenLanguage;
    @XmlElement(name = "MCAPartitionNumber", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaPartitionNumber;
    @XmlElement(name = "MCAPartitionKind", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaPartitionKind;
    @XmlElement(name = "MCATitleVersion", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaTitleVersion;
    @XmlElement(name = "MCAAudioElementKind", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaAudioElementKind;
    @XmlElement(name = "MCAAudioContentKind", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaAudioContentKind;
    @XmlElement(name = "MCAEpisode", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String mcaEpisode;
    @XmlElement(name = "MCAChannelID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String mcaChannelID;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the groupOfSoundfieldGroupsLinkID property.
     * 
     * @return
     *     possible object is
     *     {@link UUIDArray }
     *     
     */
    public UUIDArray getGroupOfSoundfieldGroupsLinkID() {
        return groupOfSoundfieldGroupsLinkID;
    }

    /**
     * Sets the value of the groupOfSoundfieldGroupsLinkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link UUIDArray }
     *     
     */
    public void setGroupOfSoundfieldGroupsLinkID(UUIDArray value) {
        this.groupOfSoundfieldGroupsLinkID = value;
    }

    /**
     * Gets the value of the mcaLinkID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCALinkID() {
        return mcaLinkID;
    }

    /**
     * Sets the value of the mcaLinkID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCALinkID(String value) {
        this.mcaLinkID = value;
    }

    /**
     * Gets the value of the mcaTagName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCATagName() {
        return mcaTagName;
    }

    /**
     * Sets the value of the mcaTagName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCATagName(UTF16String value) {
        this.mcaTagName = value;
    }

    /**
     * Gets the value of the mcaTitle property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCATitle() {
        return mcaTitle;
    }

    /**
     * Sets the value of the mcaTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCATitle(UTF16String value) {
        this.mcaTitle = value;
    }

    /**
     * Gets the value of the mcaTitleSubVersion property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCATitleSubVersion() {
        return mcaTitleSubVersion;
    }

    /**
     * Sets the value of the mcaTitleSubVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCATitleSubVersion(UTF16String value) {
        this.mcaTitleSubVersion = value;
    }

    /**
     * Gets the value of the mcaLabelDictionaryID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCALabelDictionaryID() {
        return mcaLabelDictionaryID;
    }

    /**
     * Sets the value of the mcaLabelDictionaryID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCALabelDictionaryID(String value) {
        this.mcaLabelDictionaryID = value;
    }

    /**
     * Gets the value of the mcaTagSymbol property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCATagSymbol() {
        return mcaTagSymbol;
    }

    /**
     * Sets the value of the mcaTagSymbol property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCATagSymbol(UTF16String value) {
        this.mcaTagSymbol = value;
    }

    /**
     * Gets the value of the rfc5646SpokenLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link ISO7 }
     *     
     */
    public ISO7 getRFC5646SpokenLanguage() {
        return rfc5646SpokenLanguage;
    }

    /**
     * Sets the value of the rfc5646SpokenLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link ISO7 }
     *     
     */
    public void setRFC5646SpokenLanguage(ISO7 value) {
        this.rfc5646SpokenLanguage = value;
    }

    /**
     * Gets the value of the mcaPartitionNumber property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCAPartitionNumber() {
        return mcaPartitionNumber;
    }

    /**
     * Sets the value of the mcaPartitionNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCAPartitionNumber(UTF16String value) {
        this.mcaPartitionNumber = value;
    }

    /**
     * Gets the value of the mcaPartitionKind property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCAPartitionKind() {
        return mcaPartitionKind;
    }

    /**
     * Sets the value of the mcaPartitionKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCAPartitionKind(UTF16String value) {
        this.mcaPartitionKind = value;
    }

    /**
     * Gets the value of the mcaTitleVersion property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCATitleVersion() {
        return mcaTitleVersion;
    }

    /**
     * Sets the value of the mcaTitleVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCATitleVersion(UTF16String value) {
        this.mcaTitleVersion = value;
    }

    /**
     * Gets the value of the mcaAudioElementKind property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCAAudioElementKind() {
        return mcaAudioElementKind;
    }

    /**
     * Sets the value of the mcaAudioElementKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCAAudioElementKind(UTF16String value) {
        this.mcaAudioElementKind = value;
    }

    /**
     * Gets the value of the mcaAudioContentKind property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCAAudioContentKind() {
        return mcaAudioContentKind;
    }

    /**
     * Sets the value of the mcaAudioContentKind property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCAAudioContentKind(UTF16String value) {
        this.mcaAudioContentKind = value;
    }

    /**
     * Gets the value of the mcaEpisode property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMCAEpisode() {
        return mcaEpisode;
    }

    /**
     * Sets the value of the mcaEpisode property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMCAEpisode(UTF16String value) {
        this.mcaEpisode = value;
    }

    /**
     * Gets the value of the mcaChannelID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMCAChannelID() {
        return mcaChannelID;
    }

    /**
     * Sets the value of the mcaChannelID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMCAChannelID(String value) {
        this.mcaChannelID = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
