//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._395._2014._13._1.aaf;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import org.smpte_ra.reg._2003._2012.Int64Array;
import org.smpte_ra.reg._2003._2012.UTF16String;
import org.smpte_ra.reg._2003._2012.UTF16StringArray;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ElementValues"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ElementType"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ElementNames"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MetaDefinitionName"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MetaDefinitionIdentification"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}MetaDefinitionDescription" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}uid use="required""/>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "TypeDefinitionEnumeration")
public class TypeDefinitionEnumeration {

    @XmlElement(name = "ElementValues", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected Int64Array elementValues;
    @XmlElement(name = "ElementType", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String elementType;
    @XmlElement(name = "ElementNames", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected UTF16StringArray elementNames;
    @XmlElement(name = "MetaDefinitionName", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    protected UTF16String metaDefinitionName;
    @XmlElement(name = "MetaDefinitionIdentification", namespace = "http://www.smpte-ra.org/reg/335/2012", required = true)
    @XmlSchemaType(name = "anyURI")
    protected String metaDefinitionIdentification;
    @XmlElement(name = "MetaDefinitionDescription", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected UTF16String metaDefinitionDescription;
    @XmlAttribute(name = "uid", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline", required = true)
    protected String uid;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the elementValues property.
     * 
     * @return
     *     possible object is
     *     {@link Int64Array }
     *     
     */
    public Int64Array getElementValues() {
        return elementValues;
    }

    /**
     * Sets the value of the elementValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link Int64Array }
     *     
     */
    public void setElementValues(Int64Array value) {
        this.elementValues = value;
    }

    /**
     * Gets the value of the elementType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getElementType() {
        return elementType;
    }

    /**
     * Sets the value of the elementType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setElementType(String value) {
        this.elementType = value;
    }

    /**
     * Gets the value of the elementNames property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16StringArray }
     *     
     */
    public UTF16StringArray getElementNames() {
        return elementNames;
    }

    /**
     * Sets the value of the elementNames property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16StringArray }
     *     
     */
    public void setElementNames(UTF16StringArray value) {
        this.elementNames = value;
    }

    /**
     * Gets the value of the metaDefinitionName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMetaDefinitionName() {
        return metaDefinitionName;
    }

    /**
     * Sets the value of the metaDefinitionName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMetaDefinitionName(UTF16String value) {
        this.metaDefinitionName = value;
    }

    /**
     * Gets the value of the metaDefinitionIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMetaDefinitionIdentification() {
        return metaDefinitionIdentification;
    }

    /**
     * Sets the value of the metaDefinitionIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMetaDefinitionIdentification(String value) {
        this.metaDefinitionIdentification = value;
    }

    /**
     * Gets the value of the metaDefinitionDescription property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getMetaDefinitionDescription() {
        return metaDefinitionDescription;
    }

    /**
     * Sets the value of the metaDefinitionDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setMetaDefinitionDescription(UTF16String value) {
        this.metaDefinitionDescription = value;
    }

    /**
     * Gets the value of the uid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUid() {
        return uid;
    }

    /**
     * Sets the value of the uid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUid(String value) {
        this.uid = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
