#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./dpp "$1" "../../CPL/chimera25/CPL-multiple-audio.xml" "$2/Chimera25-multiple-audio" "../chimera25/metadata-short.xml" "chimera25-multiple-audio" "$3"