#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./dpp "$1" "../../CPL/chimera25/CPL-2016-namespace.xml" "$2/Chimera25-2016-namespace" "../chimera25/metadata-short.xml" "chimera25-2016-namespace" "$3"