#!/usr/bin/env bash

function usage {
    echo "Convert all default test packages to DPP Format."
    echo "1st argument - a path to the directory containing all default test packages."
    echo "2d argument - a path to the directory containing the output for all test packages."
    echo "3d argument - a path to imf-conversion-utility (if not set a default one will be used assuming that we're in the source root folder)."
}

if [ -z "$1" ]; then
    echo "Missing argument: a path to the directory containing all default test packages."
    usage
    exit 1
fi

if [ -z "$2" ]; then
    echo "Missing argument: a path to the directory containing the output for all test packages."
    usage
    exit 1
fi

cd "${BASH_SOURCE%/*}"

Chimera23Dir="Chimera23_FTR_C_EN_XG-NR_20_4K_20150603_OV"
Chimera25Dir="Chimera25_FTR_C_EN_XG-NR_20_4K_20150608_OV"
Chimera29Dir="Chimera29_FTR_C_EN_XG-NR_20_4K_20150624_OV"
Chimera50Dir="Chimera50_FTR_C_EN_XG-NR_20_4K_20150622_OV"

# default as-is full CPLs for all test packages
./chimera23-default "$1/$Chimera23Dir" "$2" "$3";
./chimera25-default "$1/$Chimera25Dir" "$2" "$3";
./chimera50-default "$1/$Chimera50Dir" "$2" "$3";
./chimera29-default "$1/$Chimera29Dir" "$2" "$3";

# short versions
./chimera25-short "$1/$Chimera25Dir" "$2" "$3";
./chimera50-short "$1/$Chimera50Dir" "$2" "$3";
./chimera25-2016-namespace "$1/$Chimera25Dir" "$2" "$3";

# Closed Captions
./chimera29-CC "$1/$Chimera29Dir" "$2" "$3";
./chimera29-CC-short "$1/$Chimera29Dir" "$2" "$3";

# CPLs with tricky segments
./chimera25-segments "$1/$Chimera25Dir" "$2" "$3";

# no audio/video/CC
./chimera50-no-audio "$1/$Chimera50Dir" "$2" "$3";
./chimera50-no-video "$1/$Chimera50Dir" "$2" "$3";
./chimera29-CC-no-audio-no-video "$1/$Chimera29Dir" "$2" "$3";

# audiomap
./chimera25-audiomap-2A "$1/$Chimera25Dir" "$2" "$3";
./chimera25-audiomap-4B "$1/$Chimera25Dir" "$2" "$3";
./chimera25-audiomap-16C "$1/$Chimera25Dir" "$2" "$3";

# multiple
./chimera25-multiple-audio "$1/$Chimera25Dir" "$2" "$3";
