#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./itunes-audiomap "$1" "../../../CPL/chimera25/CPL-short-start-from-10-sec.xml" "$2/Chimera25-audiomap" "vendor_id" "../../chimera25/audiomap.xml" "$3"