#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./itunes-audiomap "$1" "../../../CPL/chimera25/CPL-multiple-audio-essence-desc.xml" "$2/Chimera25-essence-desc-audiomap-by-order" "vendor_id" "../../chimera25/5-6-5-fr-audiomap.xml" "$3"