#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./itunes "$1" "../../CPL/chimera25/CPL-segments-audio-essence-desc.xml" "$2/Chimera25-Segments-audio-essence-desc" "vendor_id" "$3"
