#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"

# hd

# 1080
./chimera25-format "$1" "$2" "hd1080p30"     "$3"
./chimera25-format "$1" "$2" "hd1080i2997"   "$3"
./chimera25-format "$1" "$2" "hd1080i2997"   "$3"
./chimera25-format "$1" "$2" "hd1080p2997"   "$3"
./chimera25-format "$1" "$2" "hd1080p25"     "$3"
./chimera25-format "$1" "$2" "hd1080p24"     "$3"
./chimera25-format "$1" "$2" "hd1080i23976"  "$3"
./chimera25-format "$1" "$2" "hd1080p23976"  "$3"
# 720
./chimera25-format "$1" "$2" "hd720p30"      "$3"
./chimera25-format "$1" "$2" "hd720i2997"    "$3"
./chimera25-format "$1" "$2" "hd720p2997"    "$3"
./chimera25-format "$1" "$2" "hd720p25"      "$3"
./chimera25-format "$1" "$2" "hd720p24"      "$3"
./chimera25-format "$1" "$2" "hd720i23976"   "$3"
./chimera25-format "$1" "$2" "hd720p23976"   "$3"

# sd-tv

# ntsc
./chimera25-format "$1" "$2" "sdtvntsc480i2997"  "$3"
./chimera25-format "$1" "$2" "sdtvntsc480p2997"  "$3"
./chimera25-format "$1" "$2" "sdtvntsc480p24"    "$3"
./chimera25-format "$1" "$2" "sdtvntsc480p23976" "$3"
# pal
./chimera25-format "$1" "$2" "sdtvpal576p25"     "$3"
./chimera25-format "$1" "$2" "sdtvpal576p24"     "$3"
./chimera25-format "$1" "$2" "sdtvpal576p23976"  "$3"

# sd-film

# ntsc
./chimera25-format "$1" "$2" "sdfilmntsc480i2997_16_9"   "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p2997_16_9"   "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p24_16_9"     "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p23976_16_9"  "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480i2997_4_3"    "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p2997_4_3"    "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p24_4_3"      "$3"
./chimera25-format "$1" "$2" "sdfilmntsc480p23976_4_3"   "$3"
# pal
./chimera25-format "$1" "$2" "sdfilmpal576p25_16_9"      "$3"
./chimera25-format "$1" "$2" "sdfilmpal576p24_16_9"      "$3"
./chimera25-format "$1" "$2" "sdfilmpal576p23976_16_9"   "$3"
./chimera25-format "$1" "$2" "sdfilmpal576p25_4_3"       "$3"
./chimera25-format "$1" "$2" "sdfilmpal576p24_4_3"       "$3"
./chimera25-format "$1" "$2" "sdfilmpal576p23976_4_3"    "$3"