#!/usr/bin/env bash
set -e
cd "${BASH_SOURCE%/*}"
./usage-one "$@";
./itunes-cc "$1" "../../CPL/chimera25/CPL-short.xml" "$2/Chimera25-CC" "vendor_id" "../chimera25/cc-en_US.scc" "../chimera25/cc-fr_CA.scc" "$3"