//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package ch.ebu.ebucore.smpte.class13.group;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ch.ebu.ebucore.smpte.class13.type.AudioBlockFormatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioChannelFormatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioContentStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioObjectStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioPackFormatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioProgrammeStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioStreamFormatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioTrackFormatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.AudioTrackUIDStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.Boolean;
import org.smpte_ra.reg._2003._2012.UTF16String;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioFormatExtendedDefinition" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioProgrammeObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioFormatExtendedVersion" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioFormatExtendedPresenceFlag" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioFormatExtendedId" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioFormatExtendedName" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioChannelFormatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioPackFormatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioContentObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioObjectObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioBlockFormatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioTrackUIDObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioStreamFormatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}audioTrackFormatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedDescriptiveObjectPluginID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "audioFormatExtended")
public class AudioFormatExtended {

    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String audioFormatExtendedDefinition;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioProgrammeStrongReferenceSet audioProgrammeObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String audioFormatExtendedVersion;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    @XmlSchemaType(name = "token")
    protected Boolean audioFormatExtendedPresenceFlag;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String audioFormatExtendedId;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String audioFormatExtendedName;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioChannelFormatStrongReferenceSet audioChannelFormatObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioPackFormatStrongReferenceSet audioPackFormatObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioContentStrongReferenceSet audioContentObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioObjectStrongReferenceSet audioObjectObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioBlockFormatStrongReferenceSet audioBlockFormatObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioTrackUIDStrongReferenceSet audioTrackUIDObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioStreamFormatStrongReferenceSet audioStreamFormatObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected AudioTrackFormatStrongReferenceSet audioTrackFormatObjects;
    @XmlElement(name = "LinkedDescriptiveObjectPluginID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkedDescriptiveObjectPluginID;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the audioFormatExtendedDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getAudioFormatExtendedDefinition() {
        return audioFormatExtendedDefinition;
    }

    /**
     * Sets the value of the audioFormatExtendedDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setAudioFormatExtendedDefinition(UTF16String value) {
        this.audioFormatExtendedDefinition = value;
    }

    /**
     * Gets the value of the audioProgrammeObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioProgrammeStrongReferenceSet }
     *     
     */
    public AudioProgrammeStrongReferenceSet getAudioProgrammeObjects() {
        return audioProgrammeObjects;
    }

    /**
     * Sets the value of the audioProgrammeObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioProgrammeStrongReferenceSet }
     *     
     */
    public void setAudioProgrammeObjects(AudioProgrammeStrongReferenceSet value) {
        this.audioProgrammeObjects = value;
    }

    /**
     * Gets the value of the audioFormatExtendedVersion property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getAudioFormatExtendedVersion() {
        return audioFormatExtendedVersion;
    }

    /**
     * Sets the value of the audioFormatExtendedVersion property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setAudioFormatExtendedVersion(UTF16String value) {
        this.audioFormatExtendedVersion = value;
    }

    /**
     * Gets the value of the audioFormatExtendedPresenceFlag property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean getAudioFormatExtendedPresenceFlag() {
        return audioFormatExtendedPresenceFlag;
    }

    /**
     * Sets the value of the audioFormatExtendedPresenceFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAudioFormatExtendedPresenceFlag(Boolean value) {
        this.audioFormatExtendedPresenceFlag = value;
    }

    /**
     * Gets the value of the audioFormatExtendedId property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getAudioFormatExtendedId() {
        return audioFormatExtendedId;
    }

    /**
     * Sets the value of the audioFormatExtendedId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setAudioFormatExtendedId(UTF16String value) {
        this.audioFormatExtendedId = value;
    }

    /**
     * Gets the value of the audioFormatExtendedName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getAudioFormatExtendedName() {
        return audioFormatExtendedName;
    }

    /**
     * Sets the value of the audioFormatExtendedName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setAudioFormatExtendedName(UTF16String value) {
        this.audioFormatExtendedName = value;
    }

    /**
     * Gets the value of the audioChannelFormatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioChannelFormatStrongReferenceSet }
     *     
     */
    public AudioChannelFormatStrongReferenceSet getAudioChannelFormatObjects() {
        return audioChannelFormatObjects;
    }

    /**
     * Sets the value of the audioChannelFormatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioChannelFormatStrongReferenceSet }
     *     
     */
    public void setAudioChannelFormatObjects(AudioChannelFormatStrongReferenceSet value) {
        this.audioChannelFormatObjects = value;
    }

    /**
     * Gets the value of the audioPackFormatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioPackFormatStrongReferenceSet }
     *     
     */
    public AudioPackFormatStrongReferenceSet getAudioPackFormatObjects() {
        return audioPackFormatObjects;
    }

    /**
     * Sets the value of the audioPackFormatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioPackFormatStrongReferenceSet }
     *     
     */
    public void setAudioPackFormatObjects(AudioPackFormatStrongReferenceSet value) {
        this.audioPackFormatObjects = value;
    }

    /**
     * Gets the value of the audioContentObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioContentStrongReferenceSet }
     *     
     */
    public AudioContentStrongReferenceSet getAudioContentObjects() {
        return audioContentObjects;
    }

    /**
     * Sets the value of the audioContentObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioContentStrongReferenceSet }
     *     
     */
    public void setAudioContentObjects(AudioContentStrongReferenceSet value) {
        this.audioContentObjects = value;
    }

    /**
     * Gets the value of the audioObjectObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioObjectStrongReferenceSet }
     *     
     */
    public AudioObjectStrongReferenceSet getAudioObjectObjects() {
        return audioObjectObjects;
    }

    /**
     * Sets the value of the audioObjectObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioObjectStrongReferenceSet }
     *     
     */
    public void setAudioObjectObjects(AudioObjectStrongReferenceSet value) {
        this.audioObjectObjects = value;
    }

    /**
     * Gets the value of the audioBlockFormatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioBlockFormatStrongReferenceSet }
     *     
     */
    public AudioBlockFormatStrongReferenceSet getAudioBlockFormatObjects() {
        return audioBlockFormatObjects;
    }

    /**
     * Sets the value of the audioBlockFormatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioBlockFormatStrongReferenceSet }
     *     
     */
    public void setAudioBlockFormatObjects(AudioBlockFormatStrongReferenceSet value) {
        this.audioBlockFormatObjects = value;
    }

    /**
     * Gets the value of the audioTrackUIDObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioTrackUIDStrongReferenceSet }
     *     
     */
    public AudioTrackUIDStrongReferenceSet getAudioTrackUIDObjects() {
        return audioTrackUIDObjects;
    }

    /**
     * Sets the value of the audioTrackUIDObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioTrackUIDStrongReferenceSet }
     *     
     */
    public void setAudioTrackUIDObjects(AudioTrackUIDStrongReferenceSet value) {
        this.audioTrackUIDObjects = value;
    }

    /**
     * Gets the value of the audioStreamFormatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioStreamFormatStrongReferenceSet }
     *     
     */
    public AudioStreamFormatStrongReferenceSet getAudioStreamFormatObjects() {
        return audioStreamFormatObjects;
    }

    /**
     * Sets the value of the audioStreamFormatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioStreamFormatStrongReferenceSet }
     *     
     */
    public void setAudioStreamFormatObjects(AudioStreamFormatStrongReferenceSet value) {
        this.audioStreamFormatObjects = value;
    }

    /**
     * Gets the value of the audioTrackFormatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link AudioTrackFormatStrongReferenceSet }
     *     
     */
    public AudioTrackFormatStrongReferenceSet getAudioTrackFormatObjects() {
        return audioTrackFormatObjects;
    }

    /**
     * Sets the value of the audioTrackFormatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link AudioTrackFormatStrongReferenceSet }
     *     
     */
    public void setAudioTrackFormatObjects(AudioTrackFormatStrongReferenceSet value) {
        this.audioTrackFormatObjects = value;
    }

    /**
     * Gets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedDescriptiveObjectPluginID() {
        return linkedDescriptiveObjectPluginID;
    }

    /**
     * Sets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedDescriptiveObjectPluginID(String value) {
        this.linkedDescriptiveObjectPluginID = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
