//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package ch.ebu.ebucore.smpte.class13.group;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import ch.ebu.ebucore.smpte.class13.type.CodecStrongReference;
import ch.ebu.ebucore.smpte.class13.type.FormatGroupStrongReference;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeAnyURIStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeBooleanStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeFloatStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeInt16StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeInt32StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeInt64StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeInt8StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeRationalStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeStringStrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeUInt16StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeUInt32StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeUInt64StrongReferenceSet;
import ch.ebu.ebucore.smpte.class13.type.TechnicalAttributeUInt8StrongReferenceSet;
import org.smpte_ra.reg._2003._2012.ApplicationPluginObjectStrongReferenceSet;
import org.smpte_ra.reg._2003._2012.UTF16String;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerFormatName" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerCodecObject" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerFormatVersionId" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerFormatProfile" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerFormatId" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeStringObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeAnyURIObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeRationalObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeInt8Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeBooleanObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerFormatProfileLevel" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerNote" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerEncodingFormatGroupObject" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeUInt64Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeInt16Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeInt32Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeFloatObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeInt64Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeUInt32Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeUInt8Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.ebu.ch/ebucore/smpte/class13/element}containerTechnicalAttributeUInt16Objects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedDescriptiveObjectPluginID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}InstanceID" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ObjectClass" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}ApplicationPlugInObjects" minOccurs="0"/>
 *         &lt;element ref="{http://www.smpte-ra.org/reg/335/2012}LinkedGenerationID" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute ref="{http://sandflow.com/ns/SMPTEST2001-1/baseline}path"/>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {

})
@XmlRootElement(name = "containerFormat")
public class ContainerFormat {

    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerFormatName;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected CodecStrongReference containerCodecObject;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerFormatVersionId;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerFormatProfile;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerFormatId;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeStringStrongReferenceSet containerTechnicalAttributeStringObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeAnyURIStrongReferenceSet containerTechnicalAttributeAnyURIObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeRationalStrongReferenceSet containerTechnicalAttributeRationalObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeInt8StrongReferenceSet containerTechnicalAttributeInt8Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeBooleanStrongReferenceSet containerTechnicalAttributeBooleanObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerFormatProfileLevel;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected UTF16String containerNote;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected FormatGroupStrongReference containerEncodingFormatGroupObject;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeUInt64StrongReferenceSet containerTechnicalAttributeUInt64Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeInt16StrongReferenceSet containerTechnicalAttributeInt16Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeInt32StrongReferenceSet containerTechnicalAttributeInt32Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeFloatStrongReferenceSet containerTechnicalAttributeFloatObjects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeInt64StrongReferenceSet containerTechnicalAttributeInt64Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeUInt32StrongReferenceSet containerTechnicalAttributeUInt32Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeUInt8StrongReferenceSet containerTechnicalAttributeUInt8Objects;
    @XmlElement(namespace = "http://www.ebu.ch/ebucore/smpte/class13/element")
    protected TechnicalAttributeUInt16StrongReferenceSet containerTechnicalAttributeUInt16Objects;
    @XmlElement(name = "LinkedDescriptiveObjectPluginID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String linkedDescriptiveObjectPluginID;
    @XmlElement(name = "InstanceID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String instanceID;
    @XmlElement(name = "ObjectClass", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anySimpleType")
    protected String objectClass;
    @XmlElement(name = "ApplicationPlugInObjects", namespace = "http://www.smpte-ra.org/reg/335/2012")
    protected ApplicationPluginObjectStrongReferenceSet applicationPlugInObjects;
    @XmlElement(name = "LinkedGenerationID", namespace = "http://www.smpte-ra.org/reg/335/2012")
    @XmlSchemaType(name = "anyURI")
    protected String linkedGenerationID;
    @XmlAttribute(name = "path", namespace = "http://sandflow.com/ns/SMPTEST2001-1/baseline")
    protected String path;

    /**
     * Gets the value of the containerFormatName property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerFormatName() {
        return containerFormatName;
    }

    /**
     * Sets the value of the containerFormatName property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerFormatName(UTF16String value) {
        this.containerFormatName = value;
    }

    /**
     * Gets the value of the containerCodecObject property.
     * 
     * @return
     *     possible object is
     *     {@link CodecStrongReference }
     *     
     */
    public CodecStrongReference getContainerCodecObject() {
        return containerCodecObject;
    }

    /**
     * Sets the value of the containerCodecObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link CodecStrongReference }
     *     
     */
    public void setContainerCodecObject(CodecStrongReference value) {
        this.containerCodecObject = value;
    }

    /**
     * Gets the value of the containerFormatVersionId property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerFormatVersionId() {
        return containerFormatVersionId;
    }

    /**
     * Sets the value of the containerFormatVersionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerFormatVersionId(UTF16String value) {
        this.containerFormatVersionId = value;
    }

    /**
     * Gets the value of the containerFormatProfile property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerFormatProfile() {
        return containerFormatProfile;
    }

    /**
     * Sets the value of the containerFormatProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerFormatProfile(UTF16String value) {
        this.containerFormatProfile = value;
    }

    /**
     * Gets the value of the containerFormatId property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerFormatId() {
        return containerFormatId;
    }

    /**
     * Sets the value of the containerFormatId property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerFormatId(UTF16String value) {
        this.containerFormatId = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeStringObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeStringStrongReferenceSet }
     *     
     */
    public TechnicalAttributeStringStrongReferenceSet getContainerTechnicalAttributeStringObjects() {
        return containerTechnicalAttributeStringObjects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeStringObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeStringStrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeStringObjects(TechnicalAttributeStringStrongReferenceSet value) {
        this.containerTechnicalAttributeStringObjects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeAnyURIObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeAnyURIStrongReferenceSet }
     *     
     */
    public TechnicalAttributeAnyURIStrongReferenceSet getContainerTechnicalAttributeAnyURIObjects() {
        return containerTechnicalAttributeAnyURIObjects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeAnyURIObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeAnyURIStrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeAnyURIObjects(TechnicalAttributeAnyURIStrongReferenceSet value) {
        this.containerTechnicalAttributeAnyURIObjects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeRationalObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeRationalStrongReferenceSet }
     *     
     */
    public TechnicalAttributeRationalStrongReferenceSet getContainerTechnicalAttributeRationalObjects() {
        return containerTechnicalAttributeRationalObjects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeRationalObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeRationalStrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeRationalObjects(TechnicalAttributeRationalStrongReferenceSet value) {
        this.containerTechnicalAttributeRationalObjects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeInt8Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeInt8StrongReferenceSet }
     *     
     */
    public TechnicalAttributeInt8StrongReferenceSet getContainerTechnicalAttributeInt8Objects() {
        return containerTechnicalAttributeInt8Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeInt8Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeInt8StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeInt8Objects(TechnicalAttributeInt8StrongReferenceSet value) {
        this.containerTechnicalAttributeInt8Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeBooleanObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeBooleanStrongReferenceSet }
     *     
     */
    public TechnicalAttributeBooleanStrongReferenceSet getContainerTechnicalAttributeBooleanObjects() {
        return containerTechnicalAttributeBooleanObjects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeBooleanObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeBooleanStrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeBooleanObjects(TechnicalAttributeBooleanStrongReferenceSet value) {
        this.containerTechnicalAttributeBooleanObjects = value;
    }

    /**
     * Gets the value of the containerFormatProfileLevel property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerFormatProfileLevel() {
        return containerFormatProfileLevel;
    }

    /**
     * Sets the value of the containerFormatProfileLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerFormatProfileLevel(UTF16String value) {
        this.containerFormatProfileLevel = value;
    }

    /**
     * Gets the value of the containerNote property.
     * 
     * @return
     *     possible object is
     *     {@link UTF16String }
     *     
     */
    public UTF16String getContainerNote() {
        return containerNote;
    }

    /**
     * Sets the value of the containerNote property.
     * 
     * @param value
     *     allowed object is
     *     {@link UTF16String }
     *     
     */
    public void setContainerNote(UTF16String value) {
        this.containerNote = value;
    }

    /**
     * Gets the value of the containerEncodingFormatGroupObject property.
     * 
     * @return
     *     possible object is
     *     {@link FormatGroupStrongReference }
     *     
     */
    public FormatGroupStrongReference getContainerEncodingFormatGroupObject() {
        return containerEncodingFormatGroupObject;
    }

    /**
     * Sets the value of the containerEncodingFormatGroupObject property.
     * 
     * @param value
     *     allowed object is
     *     {@link FormatGroupStrongReference }
     *     
     */
    public void setContainerEncodingFormatGroupObject(FormatGroupStrongReference value) {
        this.containerEncodingFormatGroupObject = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeUInt64Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeUInt64StrongReferenceSet }
     *     
     */
    public TechnicalAttributeUInt64StrongReferenceSet getContainerTechnicalAttributeUInt64Objects() {
        return containerTechnicalAttributeUInt64Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeUInt64Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeUInt64StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeUInt64Objects(TechnicalAttributeUInt64StrongReferenceSet value) {
        this.containerTechnicalAttributeUInt64Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeInt16Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeInt16StrongReferenceSet }
     *     
     */
    public TechnicalAttributeInt16StrongReferenceSet getContainerTechnicalAttributeInt16Objects() {
        return containerTechnicalAttributeInt16Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeInt16Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeInt16StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeInt16Objects(TechnicalAttributeInt16StrongReferenceSet value) {
        this.containerTechnicalAttributeInt16Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeInt32Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeInt32StrongReferenceSet }
     *     
     */
    public TechnicalAttributeInt32StrongReferenceSet getContainerTechnicalAttributeInt32Objects() {
        return containerTechnicalAttributeInt32Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeInt32Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeInt32StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeInt32Objects(TechnicalAttributeInt32StrongReferenceSet value) {
        this.containerTechnicalAttributeInt32Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeFloatObjects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeFloatStrongReferenceSet }
     *     
     */
    public TechnicalAttributeFloatStrongReferenceSet getContainerTechnicalAttributeFloatObjects() {
        return containerTechnicalAttributeFloatObjects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeFloatObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeFloatStrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeFloatObjects(TechnicalAttributeFloatStrongReferenceSet value) {
        this.containerTechnicalAttributeFloatObjects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeInt64Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeInt64StrongReferenceSet }
     *     
     */
    public TechnicalAttributeInt64StrongReferenceSet getContainerTechnicalAttributeInt64Objects() {
        return containerTechnicalAttributeInt64Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeInt64Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeInt64StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeInt64Objects(TechnicalAttributeInt64StrongReferenceSet value) {
        this.containerTechnicalAttributeInt64Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeUInt32Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeUInt32StrongReferenceSet }
     *     
     */
    public TechnicalAttributeUInt32StrongReferenceSet getContainerTechnicalAttributeUInt32Objects() {
        return containerTechnicalAttributeUInt32Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeUInt32Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeUInt32StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeUInt32Objects(TechnicalAttributeUInt32StrongReferenceSet value) {
        this.containerTechnicalAttributeUInt32Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeUInt8Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeUInt8StrongReferenceSet }
     *     
     */
    public TechnicalAttributeUInt8StrongReferenceSet getContainerTechnicalAttributeUInt8Objects() {
        return containerTechnicalAttributeUInt8Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeUInt8Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeUInt8StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeUInt8Objects(TechnicalAttributeUInt8StrongReferenceSet value) {
        this.containerTechnicalAttributeUInt8Objects = value;
    }

    /**
     * Gets the value of the containerTechnicalAttributeUInt16Objects property.
     * 
     * @return
     *     possible object is
     *     {@link TechnicalAttributeUInt16StrongReferenceSet }
     *     
     */
    public TechnicalAttributeUInt16StrongReferenceSet getContainerTechnicalAttributeUInt16Objects() {
        return containerTechnicalAttributeUInt16Objects;
    }

    /**
     * Sets the value of the containerTechnicalAttributeUInt16Objects property.
     * 
     * @param value
     *     allowed object is
     *     {@link TechnicalAttributeUInt16StrongReferenceSet }
     *     
     */
    public void setContainerTechnicalAttributeUInt16Objects(TechnicalAttributeUInt16StrongReferenceSet value) {
        this.containerTechnicalAttributeUInt16Objects = value;
    }

    /**
     * Gets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedDescriptiveObjectPluginID() {
        return linkedDescriptiveObjectPluginID;
    }

    /**
     * Sets the value of the linkedDescriptiveObjectPluginID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedDescriptiveObjectPluginID(String value) {
        this.linkedDescriptiveObjectPluginID = value;
    }

    /**
     * Gets the value of the instanceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInstanceID() {
        return instanceID;
    }

    /**
     * Sets the value of the instanceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInstanceID(String value) {
        this.instanceID = value;
    }

    /**
     * Gets the value of the objectClass property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getObjectClass() {
        return objectClass;
    }

    /**
     * Sets the value of the objectClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setObjectClass(String value) {
        this.objectClass = value;
    }

    /**
     * Gets the value of the applicationPlugInObjects property.
     * 
     * @return
     *     possible object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public ApplicationPluginObjectStrongReferenceSet getApplicationPlugInObjects() {
        return applicationPlugInObjects;
    }

    /**
     * Sets the value of the applicationPlugInObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link ApplicationPluginObjectStrongReferenceSet }
     *     
     */
    public void setApplicationPlugInObjects(ApplicationPluginObjectStrongReferenceSet value) {
        this.applicationPlugInObjects = value;
    }

    /**
     * Gets the value of the linkedGenerationID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkedGenerationID() {
        return linkedGenerationID;
    }

    /**
     * Sets the value of the linkedGenerationID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkedGenerationID(String value) {
        this.linkedGenerationID = value;
    }

    /**
     * Gets the value of the path property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPath() {
        return path;
    }

    /**
     * Sets the value of the path property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPath(String value) {
        this.path = value;
    }

}
