//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012._13._12.as11;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UKDPP_3D_Type_Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UKDPP_3D_Type_Enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="ThreeD_Side_by_side"/>
 *     &lt;enumeration value="ThreeD_Dual"/>
 *     &lt;enumeration value="ThreeD_Left_eye_only"/>
 *     &lt;enumeration value="ThreeD_Right_eye_only"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UKDPP_3D_Type_Enum", namespace = "http://www.smpte-ra.org/reg/2003/2012/13/12/as11")
@XmlEnum
public enum UKDPP3DTypeEnum {

    @XmlEnumValue("ThreeD_Side_by_side")
    THREE_D_SIDE_BY_SIDE("ThreeD_Side_by_side"),
    @XmlEnumValue("ThreeD_Dual")
    THREE_D_DUAL("ThreeD_Dual"),
    @XmlEnumValue("ThreeD_Left_eye_only")
    THREE_D_LEFT_EYE_ONLY("ThreeD_Left_eye_only"),
    @XmlEnumValue("ThreeD_Right_eye_only")
    THREE_D_RIGHT_EYE_ONLY("ThreeD_Right_eye_only");
    private final String value;

    UKDPP3DTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UKDPP3DTypeEnum fromValue(String v) {
        for (UKDPP3DTypeEnum c: UKDPP3DTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
