//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.08.11 at 01:51:42 PM MSK 
//


package org.smpte_ra.reg._2003._2012._13._12.as11;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UKDPP_Audio_Loudness_Standard_Enum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="UKDPP_Audio_Loudness_Standard_Enum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *     &lt;enumeration value="Loudness_None"/>
 *     &lt;enumeration value="Loudness_EBU_R_128"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "UKDPP_Audio_Loudness_Standard_Enum", namespace = "http://www.smpte-ra.org/reg/2003/2012/13/12/as11")
@XmlEnum
public enum UKDPPAudioLoudnessStandardEnum {

    @XmlEnumValue("Loudness_None")
    LOUDNESS_NONE("Loudness_None"),
    @XmlEnumValue("Loudness_EBU_R_128")
    LOUDNESS_EBU_R_128("Loudness_EBU_R_128");
    private final String value;

    UKDPPAudioLoudnessStandardEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static UKDPPAudioLoudnessStandardEnum fromValue(String v) {
        for (UKDPPAudioLoudnessStandardEnum c: UKDPPAudioLoudnessStandardEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
